export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";
export const FETCHING_AREA_DATA = "FETCHING_AREA_DATA";
export const FETCHING_AREA_DATA_SUCCESS = "FETCHING_AREA_DATA_SUCCESS";
export const FETCHING_AREA_DATA_FAILURE = "FETCHING_AREA_DATA_FAILURE";
export const FETCHING_DATA_NETWORK = "FETCHING_DATA_NETWORK";
export const FETCHING_DATA_SUCCESS_NETWORK = "FETCHING_DATA_SUCCESS_NETWORK";
export const FETCHING_DATA_FAILURE_NETWORK = "FETCHING_DATA_FAILURE_NETWORK";

